[project]

name = "diffusion-wm-policies"
requires-python = ">=3.10"
version = "0.1.0"
packages = ["wmp"]

dependencies = [
    "av>=15.0.0",
    "tensorboard>=2.20.0",
    "torch>=2.8.0",
    "torchvision>=0.23.0",
    "transformers>=4.53.3",
]
